class/cilium.yml, class/defaults.yml, component/olm.jsonnet, docs/modules/ROOT/pages/references/parameters.adoc
This commit prepares the component to support both opensource and enterprise OLM installations.
The component, however, doesn't provide the Enterprise OLM .tar.gz URL. Users must provide the URL themselves in their Project Syn configuration in parameter `cilium.olm.source.enterprise`.
Fixes #16
=> Add support for Cilium Enterprise OLM installation

class/defaults.yml, tests/golden/defaults/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-configmap.yaml, tests/golden/helm-opensource/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-configmap.yaml, tests/golden/olm-opensource/cilium/cilium/olm/cluster-network-07-cilium-ciliumconfig.yaml
This parameter is only used for Cilium's "Native-Routing" mode (cf. https://docs.cilium.io/en/v1.11/concepts/networking/routing/#native-routing), which is not enabled by default.
This PR removes the parameter from the default configuration since it has no effect on its own.
=> Remove default value for `nativeRoutingCIDR`

class/cilium.yml, component/aggregated-clusterroles.jsonnet, docs/modules/ROOT/pages/index.adoc, tests/golden/defaults/cilium/cilium/02_aggregated_clusterroles.yaml, tests/golden/helm-opensource/cilium/cilium/02_aggregated_clusterroles.yaml, tests/golden/olm-opensource/cilium/cilium/02_aggregated_clusterroles.yaml
We aggregate `ciliumnetworkpolicies` to `view` and `edit`, `ciliumendpoints` to `view`, and all resources in `cilium.io` to `cluster-reader`.
As far as I can see, it's fine to allow users to manage `ciliumnetworkpolicies` and view `ciliumendpoints` in their namespaces.
=> Create aggregated clusterroles for `cilium.io` resources

.gitignore, component/olm.jsonnet, tests/golden/defaults/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-agent/daemonset.yaml, tests/golden/helm-opensource/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-agent/daemonset.yaml, tests/golden/olm-opensource/cilium/cilium/olm/99_cleanup.yaml
Some Cilium EE OLM tar-balls have a different directory structure. This PR adjusts the component to be able to handle both structures which we've observed so far. Additionally, an explicit error message is thrown when neither structure is found in the unpacked tar-ball.
This fixes the component for installing Cililum EE OLM 1.11.17 (and possibly other 1.11 patch releases).
Notably the tar-ball for Cilium EE OLM 1.12.6 is using the "old" format again.
changelog.
=> Make Cilium OLM tar-ball loading more robust

component/olm.jsonnet
Some Cilium EE OLM tar-balls contain hidden files (e.g. 1.12.6), which we're not interested in. Additionally, these files break `kap.yaml_load()` because they don't contain valid YAML.
changelog.
=> Ignore hidden files when loading OLM manifests

component/olm.jsonnet
The Cilium EE 1.13.2 OLM tarball has yet another directory structure. This commit refactors the component to go through a list of possible directories until it finds one that exists for the requested Cilium EE OLM version.
Follow-up for #75 
changelog.
=> Add support for more tarball structures

class/defaults.yml, tests/golden/defaults/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-configmap.yaml, tests/golden/helm-opensource/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-configmap.yaml, tests/golden/olm-opensource/cilium/cilium/olm/cluster-network-07-cilium-ciliumconfig.yaml
Enable kube-proxy replacement for host, hostPort, nodePort and externalIP services. Additionally, explicitly select `ensX` interface for direct routing for nodePort services and enable session affinity. This config should roughly replicate the config we previously had with `kubeProxyReplacement: probe`.
This is in preparation for Cilium 1.13 which removes `kubeProxyReplacement: probe`.
Factored out from #78 
changelog.
=> Switch to `kubeProxyReplacement: partial`

component/olm.jsonnet, tests/golden/olm-opensource/cilium/cilium/olm/cluster-network-06-cilium-00002-cilium-olm-deployment.yaml, tests/golden/olm-opensource/cilium/cilium/olm/cluster-network-06-cilium-00014-cilium.v1.13.8-xe0355c7-clusterserviceversion.yaml, tests/golden/olm-opensource/cilium/cilium/olm/cluster-network-07-cilium-ciliumconfig.yaml, tests/olm-opensource.yml
We set the environment variables in the `cilium-ee-olm-overrides` configmap when deploying Cilium EE via OLM and we patch the OLM deployment when deploying Cilium OSS via OLM.
changelog.
=> Inject K8s service host/port into OLM deployment

class/defaults.yml, tests/golden/defaults/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-configmap.yaml, tests/golden/egress-gateway/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-configmap.yaml, tests/golden/helm-opensource/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-configmap.yaml, tests/golden/olm-opensource/cilium/cilium/olm/cluster-network-07-cilium-ciliumconfig.yaml
As long as we use `kubeProxyReplacement=partial` as the default, we need to disable NodePort health checks in the defaults, as kube-proxy will also deploy a health-check listener for services with `type=LoadBalancer` and `externalTrafficPolicy=Local`.
changelog.
=> Disable NodePort health checks by default

component/aggregated-clusterroles.jsonnet, tests/golden/defaults/cilium/cilium/02_aggregated_clusterroles.yaml, tests/golden/egress-gateway/cilium/cilium/02_aggregated_clusterroles.yaml, tests/golden/helm-opensource/cilium/cilium/02_aggregated_clusterroles.yaml, tests/golden/olm-opensource/cilium/cilium/02_aggregated_clusterroles.yaml
The correct resource is `ciliumnetworkpolicies` and not `networkpolicies`.
changelog.
=> Fix Cilium NetworkPolicy rules in aggregated clusterroles

component/egress-gateway-policies.jsonnet, tests/golden/egress-gateway/cilium/cilium/20_egress_gateway_policies.yaml
The cilium-operator only deploys the custom resource after the feature is enabled. If we try to enable the feature and deploy policies at the same time, the ArgoCD sync will fail unless we tell ArgoCD to skip the dry-run for the policies.
changelog.
=> Set `SkipDryRunOnMissingResource=true` on egress gateway policies

class/defaults.yml, component/olm.jsonnet, docs/modules/ROOT/pages/references/parameters.adoc, tests/golden/olm-opensource/cilium/cilium/olm/cluster-network-06-cilium-00002-cilium-olm-deployment.yaml, tests/golden/olm-opensource/cilium/cilium/olm/cluster-network-06-cilium-00014-cilium.v1.13.8-xe0355c7-clusterserviceversion.yaml
The upstream configuration enables `--zap-devel` which enables debug logging. We don't need or want this for production deployments.
This PR introduces a parameter `olm.log_level` which is used to set `--zap-log-level` for the OLM operator.
changelog.
=> Add support for configuring OLM operator log level

class/defaults.yml, component/egress-gateway-policies.jsonnet, docs/modules/ROOT/pages/references/parameters.adoc, tests/egress-gateway.yml, tests/golden/egress-gateway/cilium/cilium/20_namespace_egress_ip_policies.yaml, tests/golden/egress-gateway/cilium/cilium/30_egress_ip_shadow_ranges.yaml
See also https://github.com/appuio/component-openshift4-nodes/pull/76
changelog.
=> Add support for deploying a configmap holding egress IP shadow ranges

component/aggregated-clusterroles.jsonnet, component/egress-gateway-policies.jsonnet, tests/golden/defaults/cilium/cilium/02_aggregated_clusterroles.yaml, tests/golden/egress-gateway/cilium/cilium/02_aggregated_clusterroles.yaml, tests/golden/egress-gateway/cilium/cilium/20_egress_gateway_policies.yaml, tests/golden/egress-gateway/cilium/cilium/20_namespace_egress_ip_policies.yaml, tests/golden/helm-opensource/cilium/cilium/02_aggregated_clusterroles.yaml, tests/golden/olm-opensource/cilium/cilium/02_aggregated_clusterroles.yaml
We ensure that `CiliumEgressGatewayPolicy` resources aren't pruned automatically, so that we'll be able to migrate to `IsovalentEgressGatewayPolicy` resources without interruptions of egress traffic.
changelog.
=> Prepare migration to `IsovalentEgressGatewayPolicy` resources

class/defaults.yml, component/olm.jsonnet, tests/golden/olm-opensource/cilium/cilium/olm/98_fixup_bgp_controlpane_rbac.yaml, tests/golden/olm-opensource/cilium/cilium/olm/cluster-network-07-cilium-ciliumconfig.yaml
When enabling the BGP control plane feature, the OLM operator needs to create a Role and RoleBinding for read-only access to Secrets in the `kube-system` namespace. In Cilium <= 1.14, there's no way to change the namespace which the OLM operator configures as the source for BGP peering secrets to something other than `kube-system`.
However, if Cilium is installed in a namespace other than `kube-system`, such as `cilium`, the OLM operator doesn't have sufficient permissions to create the required Role and RoleBinding in the `kube-system` namespace.
This commit generates RBAC rules which ensure that the OLM operator can create the required RBAC rules in the kube-system namespace.
See also https://github.com/cilium/cilium/issues/31499
Note that this shouldn't be necessary anymore for Cilium …
=> Create RBAC to grant the OLM operator read-only access to Secrets in `kube-system`

class/defaults.yml, tests/golden/bgp-control-plane/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-configmap.yaml, tests/golden/defaults/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-configmap.yaml, tests/golden/egress-gateway/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-configmap.yaml, tests/golden/helm-opensource/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-configmap.yaml, tests/golden/kubeproxyreplacement-strict/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-configmap.yaml, tests/golden/olm-opensource/cilium/cilium/olm/cluster-network-07-cilium-ciliumconfig.yaml
This isn't a breaking change, since our previous `kubeProxyReplacement=partial` configuration was already functionally equivalent to `kubeProxyReplacement="true"/strict`, cf. the note in https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#kube-proxy-hybrid-modes
changelog.
=> Update component defaults to set `kubeProxyReplacement="true"`

class/defaults.yml, component/render-helm-values.jsonnet, docs/modules/ROOT/pages/references/parameters.adoc, tests/golden/bgp-control-plane/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-configmap.yaml, tests/golden/defaults/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-configmap.yaml, tests/golden/helm-opensource/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-configmap.yaml, tests/golden/kubeproxyreplacement-strict/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-configmap.yaml, tests/golden/olm-opensource/cilium/cilium/olm/cluster-network-07-cilium-ciliumconfig.yaml
We change the component defaults to enable BPF masquerading. See https://docs.cilium.io/en/stable/network/concepts/masquerading/#ebpf-based for details.
The component will force-enable BPF masquerading if the user has enabled the Egress Gateway (or Egress Gateway HA) feature.
changelog.
=> Enable BPF masquerading by default

class/cilium.yml, class/defaults.yml, component/l2-announcement-policies.jsonnet, docs/modules/ROOT/pages/references/parameters.adoc, tests/golden/bgp-control-plane/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-configmap.yaml, tests/golden/defaults/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-configmap.yaml, tests/golden/egress-gateway/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-configmap.yaml, tests/golden/helm-opensource/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-configmap.yaml, tests/golden/kubeproxyreplacement-strict/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-configmap.yaml, tests/golden/l2-announcement/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-agent/clusterrole.yaml, tests/golden/l2-announcement/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-configmap.yaml, tests/golden/l2-announcement/cilium/cilium/40_l2_announcement_policies.yaml, tests/golden/olm-opensource/cilium/cilium/olm/cluster-network-07-cilium-ciliumconfig.yaml, tests/l2-announcement.yml
L2 Announcements is a feature which makes services visible and reachable on the local area network. This feature is primarily intended for on-premises deployments within networks without BGP based routing.
changelog.
=> Support deploying CiliumL2AnnouncementPolicies

class/defaults.yml, component/bgp-control-plane.jsonnet, component/l2-announcement-policies.jsonnet, component/olm.jsonnet, component/util.libsonnet, docs/modules/ROOT/pages/references/parameters.adoc, tests/golden/l2-announcement/cilium/cilium/50_loadbalancer_ip_pools.yaml, tests/l2-announcement.yml
Moves the LB IP Pool generating code to a utility class and allow defining LB IP Pools in L2 Announcements config as well.
changelog.
=> Allow creating CiliumLoadBalancerIPPool with L2 Announcements

component/cleanup.libsonnet, tests/golden/olm-opensource/cilium/cilium/olm/99_cleanup.yaml
By turning the required SA into a PreSync hook, it gets created before the job which uses it.
Tested on the new cluster by deleting the service account and then syncing.
changelog.
=> Fix bootstrapping issue in PreSync hook

component/olm.jsonnet, tests/golden/olm-opensource/cilium/cilium/olm/cluster-network-06-cilium-00008-cilium-cilium-olm-clusterrole.yaml
The Cilium Helm chart for cilium <= 1.15 uses a ClusterRole and ClusterRoleBinding for the Hubble certgen CronJob. This is changed to a Role and RoleBinding for the Cilium 1.16 Helm chart.
The OLM operator doesn't have permissions to create the ClusterRole and ClusterRoleBinding out of the box, so we patch the OLM operator ClusterRole to contain the rules that need to be created for the certgen CronJob.
changelog.
=> Patch OLM RBAC to allow deploying Hubble certgen cronjob

component/olm.jsonnet, tests/golden/olm-opensource/cilium/cilium/olm/cluster-network-06-cilium-00005-cilium-olm-role.yaml
This is required when setting `method: certmanager` for some Cilium TLS configuration (e.g. Hubble TLS).
changelog.
=> Grant OLM operator permissions to manage cert-manager certificates

component/egress-gateway-policies.jsonnet
There's no reason to disallow egress ranges with one IP (start == end) when creating namespace policies, since we use inclusive ranges for the rest of the implementation.
The documentation already notes that validation checks whether the first IP is **larger than** the last IP.
changelog.
=> Fix check for empty egress range in `NamespaceEgressPolicy`

component/egress-gateway-policies.jsonnet, docs/modules/ROOT/pages/references/parameters.adoc
This is helpful for clusters that use self service namespace egress IPs (cf. #159) as well as clusters that only use the shadow ranges part of `egress_ip_ranges`.
changelog.
=> Make field `namespace_egress_ips` in `egress_ip_ranges` optional

class/defaults.yml, component/bgp-control-plane.jsonnet, docs/modules/ROOT/pages/references/parameters.adoc, tests/bgp-control-plane.yml, tests/golden/bgp-control-plane/cilium/cilium/40_bgp_advertisements.yaml, tests/golden/bgp-control-plane/cilium/cilium/40_bgp_auth_secrets.yaml, tests/golden/bgp-control-plane/cilium/cilium/40_bgp_cluster_configs.yaml, tests/golden/bgp-control-plane/cilium/cilium/40_bgp_peer_configs.yaml
Th PR adds support for configuring BGP control plane v2 resources (`CiliumBGPClusterConfig` , `CiliumBGPPeerConfig` , `CiliumBGPAdvertisement`, `CiliumBGPNodeConfigOverride` and BGP auth `Secret`). The PR also adds basic validation for the `CiliumBGPPeerConfig` references in `CiliumBGPClusterConfig` resources and the auth secret references in `CiliumBGPPeerConfig`.
changelog.
=> Add support for managing Cilium BGP control plane v2 manifests

component/bgp-control-plane.jsonnet, docs/modules/ROOT/pages/references/parameters.adoc, tests/golden/bgp-control-plane/cilium/cilium/40_bgp_auth_secrets.yaml
We adjust the BGP auth secret generation to always set `metadata.namespace` of the resulting secrets to the configured BGP control plane secrets namespace by reading `cilium_helm_values.bgpControlPlane.secretsNamespace.name`.
This should reduce the potential for unexpected misconfigurations.
changelog.
=> Always deploy BGP auth secrets in the configured secrets namespace

component/bgp-control-plane.jsonnet, tests/bgp-control-plane.yml
We preprocess the `bgp` parameters which are passed to `com.generateResources()`, so we need to check for null values ourselves in the preprocessing.
changelog.
=> Correctly handle nulled BGP resource configuration entries

.cruft.json, .github/workflows/test.yaml, Makefile.vars.mk, class/defaults.yml, component/bgp-control-plane.jsonnet, component/olm.jsonnet, component/render-helm-values.jsonnet, docs/modules/ROOT/pages/references/parameters.adoc, tests/enterprise-bgp.yml, tests/golden/enterprise-bgp/cilium/cilium/02_aggregated_clusterroles.yaml, tests/golden/enterprise-bgp/cilium/cilium/10_ebpf_alerts.yaml, tests/golden/enterprise-bgp/cilium/cilium/40_bgp_cluster_configs.yaml, tests/golden/enterprise-bgp/cilium/cilium/40_bgp_peer_configs.yaml, tests/golden/enterprise-bgp/cilium/cilium/olm/99_cleanup.yaml, tests/golden/enterprise-bgp/cilium/cilium/olm/cluster-network-03-cilium-ciliumconfigs-crd.yaml, tests/golden/enterprise-bgp/cilium/cilium/olm/cluster-network-06-cilium-00000-cilium-namespace.yaml, tests/golden/enterprise-bgp/cilium/cilium/olm/cluster-network-06-cilium-00001-cilium-olm-serviceaccount.yaml, tests/golden/enterprise-bgp/cilium/cilium/olm/cluster-network-06-cilium-00002-cilium-olm-deployment.yaml, tests/golden/enterprise-bgp/cilium/cilium/olm/cluster-network-06-cilium-00003-cilium-olm-service.yaml, tests/golden/enterprise-bgp/cilium/cilium/olm/cluster-network-06-cilium-00004-cilium-olm-leader-election-role.yaml, tests/golden/enterprise-bgp/cilium/cilium/olm/cluster-network-06-cilium-00005-cilium-olm-role.yaml, tests/golden/enterprise-bgp/cilium/cilium/olm/cluster-network-06-cilium-00006-leader-election-rolebinding.yaml, tests/golden/enterprise-bgp/cilium/cilium/olm/cluster-network-06-cilium-00007-cilium-olm-rolebinding.yaml, tests/golden/enterprise-bgp/cilium/cilium/olm/cluster-network-06-cilium-00008-cilium-cilium-olm-clusterrole.yaml, tests/golden/enterprise-bgp/cilium/cilium/olm/cluster-network-06-cilium-00009-cilium-cilium-clusterrole.yaml, tests/golden/enterprise-bgp/cilium/cilium/olm/cluster-network-06-cilium-00010-cilium-cilium-olm-clusterrolebinding.yaml, tests/golden/enterprise-bgp/cilium/cilium/olm/cluster-network-06-cilium-00011-cilium-cilium-clusterrolebinding.yaml, tests/golden/enterprise-bgp/cilium/cilium/olm/cluster-network-06-cilium-00012-cilium-operatorgroup.yaml, tests/golden/enterprise-bgp/cilium/cilium/olm/cluster-network-06-cilium-00014-cilium.v1.15.1-x7095b76-clusterserviceversion.yaml, tests/golden/enterprise-bgp/cilium/cilium/olm/cluster-network-07-cilium-ciliumconfig.yaml
The enterprise BGP control plane is required for enterprise-only BGP features (e.g. EGW-HA BGP announcements).
changelog.
=> Add support for configuring Enterprise BGP control plane
